### ISSUE TITLE
pip2tgz PyPDF2-....

### ISSUE THREAD

**Issue by tome-** [duncan-roe/pip2tgz#1]
there is a bug for pip2tgz PyPDF2-2.12.1.tar.gz

pip2tgz PyPDF2-2.12.1.tar.gz
/usr/bin/pip2tgz: line 111: cd: PyPDF2-revs: No such file or directory

`tar tf PyPDF2-2.12.1.tar.gz | head -n1 | rev | cut -f1 -d- | rev | cut -f1 -d/`
revs                                but should be 2.12.1

`tar tf PyPDF2-2.12.1.tar.gz `
PyPDF2-2.12.1/.git-blame-ignore-revs
PyPDF2-2.12.1/CHANGELOG.md
...

problem:
`VERSION=$(tar tf $PACKAGE | head -n1 | rev | cut -f1 -d- | rev | cut -f1 -d/)`
should be?:
`VERSION=$(tar tf $PACKAGE | head -n1 | cut -f1 -d/ | rev | cut -f1 -d- | rev)`

Next bug is:
cp: cannot stat 'setup.py': No such file or directory

`cp -a setup.py $PKG/usr/doc/$PKGNAM-$VERSION`
should be?:
`cp -a setup.* $PKG/usr/doc/$PKGNAM-$VERSION`

FYI:
Another, more complicated pip2tgz (convert of .tar.gz and zip compressed .whl) is here:
https://codeberg.org/h3xx/pip2tgz

**Comment by duncan-roe** [comment]
Hi,

First of all: SBo package python3-PyPDF2 is already at 2.12.1.

On Wed, Jan 03, 2024 at 03:32:41PM -0800, tome- wrote:
> there is a bug for pip2tgz PyPDF2-2.12.1.tar.gz
>
> pip2tgz PyPDF2-2.12.1.tar.gz
> /usr/bin/pip2tgz: line 111: cd: PyPDF2-revs: No such file or directory
>
> `tar tf PyPDF2-2.12.1.tar.gz | head -n1 | rev | cut -f1 -d- | rev | cut -f1 -d/`
> revs                                but should be 2.12.1
>
> `tar tf PyPDF2-2.12.1.tar.gz `
> PyPDF2-2.12.1/.git-blame-ignore-revs

Ouch! filename contains minus signs.

All tar archives I've looked at before start with a line with no filename.

> PyPDF2-2.12.1/CHANGELOG.md
> ...
>
> problem:
> `VERSION=$(tar tf $PACKAGE | head -n1 | rev | cut -f1 -d- | rev | cut -f1 -d/)`
> should be?:
> `VERSION=$(tar tf $PACKAGE | head -n1 | cut -f1 -d/ | rev | cut -f1 -d- | rev)`

Yes that fixes it, thanks.
>
> Next bug is:
> cp: cannot stat 'setup.py': No such file or directory
>
> `cp -a setup.py $PKG/usr/doc/$PKGNAM-$VERSION`
> should be?:
> `cp -a setup.* $PKG/usr/doc/$PKGNAM-$VERSION`

Thanks that will fix it for now (until thare is no setup.*).
>
> FYI:
> Another, more complicated pip2tgz (convert of .tar.gz and zip compressed .whl)
> is here:
> https://codeberg.org/h3xx/pip2tgz
>
Might switch over to using that since it can do .whl which the current pip2tgz
can't.

Cheers .. Duncan.

**Comment by duncan-roe** [comment]
Fixed in version 0.9
